# Generated by cucumber-sinatra. (Mon Dec 13 11:55:05 +0100 2010)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'coming_soon.rb')

require 'capybara'
require 'capybara/cucumber'

Capybara.app = ComingSoon

class ComingSoonWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ComingSoonWorld.new
end

begin
  require 'database_cleaner'
  DatabaseCleaner.strategy = :truncation
  DatabaseCleaner.clean
rescue LoadError => ignore_if_database_cleaner_not_present
end
