# Generated by cucumber-sinatra. (Mon Dec 13 11:55:05 +0100 2010)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'coming_soon.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Capybara.app = ComingSoon

class ComingSoonWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  ComingSoonWorld.new
end
